# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cnc.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(291, 314)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmbPort = QtWidgets.QComboBox(self.centralwidget)
        self.cmbPort.setGeometry(QtCore.QRect(10, 30, 151, 23))
        self.cmbPort.setObjectName("cmbPort")
        self.cmbPort.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 59, 15))
        self.label.setObjectName("label")
        self.btnBaglan = QtWidgets.QPushButton(self.centralwidget)
        self.btnBaglan.setGeometry(QtCore.QRect(170, 10, 111, 23))
        self.btnBaglan.setObjectName("btnBaglan")
        self.btnKes = QtWidgets.QPushButton(self.centralwidget)
        self.btnKes.setGeometry(QtCore.QRect(170, 30, 111, 23))
        self.btnKes.setObjectName("btnKes")
        self.btnHome = QtWidgets.QPushButton(self.centralwidget)
        self.btnHome.setGeometry(QtCore.QRect(10, 140, 71, 51))
        self.btnHome.setObjectName("btnHome")
        self.btnYukari = QtWidgets.QPushButton(self.centralwidget)
        self.btnYukari.setGeometry(QtCore.QRect(100, 60, 81, 41))
        self.btnYukari.setObjectName("btnYukari")
        self.btnAsagi = QtWidgets.QPushButton(self.centralwidget)
        self.btnAsagi.setGeometry(QtCore.QRect(100, 150, 81, 41))
        self.btnAsagi.setObjectName("btnAsagi")
        self.btnSaga = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaga.setGeometry(QtCore.QRect(140, 100, 51, 51))
        self.btnSaga.setObjectName("btnSaga")
        self.btnSola = QtWidgets.QPushButton(self.centralwidget)
        self.btnSola.setGeometry(QtCore.QRect(90, 100, 51, 51))
        self.btnSola.setObjectName("btnSola")
        self.btnUcYukari = QtWidgets.QPushButton(self.centralwidget)
        self.btnUcYukari.setGeometry(QtCore.QRect(200, 60, 81, 61))
        self.btnUcYukari.setObjectName("btnUcYukari")
        self.btnUcAsagi = QtWidgets.QPushButton(self.centralwidget)
        self.btnUcAsagi.setGeometry(QtCore.QRect(200, 130, 81, 61))
        self.btnUcAsagi.setObjectName("btnUcAsagi")
        self.txtDosya = QtWidgets.QLineEdit(self.centralwidget)
        self.txtDosya.setGeometry(QtCore.QRect(10, 220, 131, 23))
        self.txtDosya.setObjectName("txtDosya")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 59, 15))
        self.label_2.setObjectName("label_2")
        self.btnBaslat = QtWidgets.QPushButton(self.centralwidget)
        self.btnBaslat.setGeometry(QtCore.QRect(200, 200, 81, 23))
        self.btnBaslat.setObjectName("btnBaslat")
        self.btnDurdur = QtWidgets.QPushButton(self.centralwidget)
        self.btnDurdur.setGeometry(QtCore.QRect(200, 220, 81, 23))
        self.btnDurdur.setObjectName("btnDurdur")
        self.cmbAdimHiz = QtWidgets.QComboBox(self.centralwidget)
        self.cmbAdimHiz.setGeometry(QtCore.QRect(10, 80, 71, 23))
        self.cmbAdimHiz.setObjectName("cmbAdimHiz")
        self.cmbAdimHiz.addItem("")
        self.cmbAdimHiz.addItem("")
        self.cmbAdimHiz.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_3.setObjectName("label_3")
        self.btnDosyaSec = QtWidgets.QPushButton(self.centralwidget)
        self.btnDosyaSec.setGeometry(QtCore.QRect(150, 200, 51, 41))
        self.btnDosyaSec.setObjectName("btnDosyaSec")
        self.ilerleme = QtWidgets.QProgressBar(self.centralwidget)
        self.ilerleme.setGeometry(QtCore.QRect(10, 270, 271, 31))
        self.ilerleme.setProperty("value", 0)
        self.ilerleme.setObjectName("ilerleme")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 250, 59, 15))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cmbPort.currentIndexChanged['QString'].connect(MainWindow.getText)
        self.cmbAdimHiz.currentIndexChanged['QString'].connect(MainWindow.getSpeed)
        self.btnBaglan.clicked.connect(MainWindow.baglan)
        self.btnKes.clicked.connect(MainWindow.baglantiKes)
        self.btnUcYukari.pressed.connect(MainWindow.ucYukari)
        self.btnUcAsagi.pressed.connect(MainWindow.ucAsagi)
        self.btnYukari.pressed.connect(MainWindow.yukari)
        self.btnAsagi.pressed.connect(MainWindow.asagi)
        self.btnSola.pressed.connect(MainWindow.sola)
        self.btnSaga.pressed.connect(MainWindow.saga)
        self.btnHome.clicked.connect(MainWindow.home)
        self.btnDosyaSec.clicked.connect(MainWindow.dosyaSec)
        self.btnBaslat.clicked.connect(MainWindow.baslat)
        self.btnDurdur.clicked.connect(MainWindow.durdur)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cmbPort.setItemText(0, _translate("MainWindow", "port"))
        self.label.setText(_translate("MainWindow", "Seri port"))
        self.btnBaglan.setText(_translate("MainWindow", "Bağlan"))
        self.btnKes.setText(_translate("MainWindow", "Bağlantıyı kes"))
        self.btnHome.setText(_translate("MainWindow", "HOME"))
        self.btnYukari.setText(_translate("MainWindow", "YUKARI"))
        self.btnAsagi.setText(_translate("MainWindow", "AŞAĞI"))
        self.btnSaga.setText(_translate("MainWindow", "SAĞA"))
        self.btnSola.setText(_translate("MainWindow", "SOLA"))
        self.btnUcYukari.setText(_translate("MainWindow", "KALEM\n"
"YUKARI"))
        self.btnUcAsagi.setText(_translate("MainWindow", "KALEM\n"
"AŞAĞI"))
        self.label_2.setText(_translate("MainWindow", "Dosya"))
        self.btnBaslat.setText(_translate("MainWindow", "BAŞLAT"))
        self.btnDurdur.setText(_translate("MainWindow", "DURDUR"))
        self.cmbAdimHiz.setItemText(0, _translate("MainWindow", "0.001"))
        self.cmbAdimHiz.setItemText(1, _translate("MainWindow", "0.010"))
        self.cmbAdimHiz.setItemText(2, _translate("MainWindow", "0.100"))
        self.label_3.setText(_translate("MainWindow", "Adım(inch)"))
        self.btnDosyaSec.setText(_translate("MainWindow", "Dosya\n"
"Seç"))
        self.label_4.setText(_translate("MainWindow", "Ilerleme"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
